kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/{{ CAPI_VERSION }}
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
spec:
  rolloutStrategy:
    rollingUpdate:
      maxSurge: ${ MAX_SURGE_VALUE }
  replicas: ${ NUM_OF_MASTER_REPLICAS }
  version: ${ KUBERNETES_VERSION }
{% if CAPI_VERSION == "v1alpha3" %}
  nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
  infrastructureTemplate:
    kind: Metal3MachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
    name: ${ CLUSTER_NAME }-controlplane
{% else %}
  machineTemplate:
    nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
    infrastructureRef:
      kind: Metal3MachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
      name: ${ CLUSTER_NAME }-controlplane
{% endif %}
  kubeadmConfigSpec:
    clusterConfiguration: {}
    joinConfiguration:
      controlPlane: {}
      nodeRegistration:
        name: "{{ '{{ ds.meta_data.name }}' }}"
        kubeletExtraArgs:
          node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
          provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
          feature-gates: "AllAlpha=false"
          container-runtime: "remote"
          cgroup-driver: "systemd"
          container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
          runtime-request-timeout: "5m"
    initConfiguration:
      nodeRegistration:
        name: "{{ '{{ ds.meta_data.name }}' }}"
        kubeletExtraArgs:
          node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
          provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
          feature-gates: "AllAlpha=false"
          container-runtime: "remote"
          cgroup-driver: "systemd"
          container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
          runtime-request-timeout: "5m"
    users:
    - name: {{ IMAGE_USERNAME }}
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - {{ SSH_PUB_KEY_CONTENT }}
{% filter indent(width=4, first=True) %}
{% include "cluster-template-controlplane-kubeadm-config-%s.yaml" % (IMAGE_OS | lower) %}
{% endfilter %}

---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
kind: Metal3MachineTemplate
metadata:
  name: ${ CLUSTER_NAME }-controlplane
  namespace: ${ NAMESPACE }
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
        checksumType: {{ IMAGE_CHECKSUM_TYPE }}
        format: {{ IMAGE_FORMAT }}
      dataTemplate:
        name: ${ CLUSTER_NAME }-controlplane-template
---
{% with template_type="controlplane" %}
{% include "metal3datatemplate-template.yaml" %}
{% endwith %}
