# CentOS specific worker kubeadm config
preKubeadmCommands:
  - systemctl restart NetworkManager.service
  - ifup eth0
  - systemctl enable --now crio kubelet
files:
  - path: /usr/local/bin/retrieve.configuration.files.sh
    owner: root:root
    permissions: '0755'
    content: |
        #!/bin/bash
        set -e
        url="$1"
        dst="$2"
        filename="$(basename $url)"
        tmpfile="/tmp/$filename"
        curl -sSL -w "%{http_code}" "$url" | sed "s:/usr/bin:/usr/local/bin:g" > /tmp/"$filename"
        http_status=$(cat "$tmpfile" | tail -n 1)
        if [ "$http_status" != "200" ]; then
          echo "Error: unable to retrieve $filename file";
          exit 1;
        else
          cat "$tmpfile"| sed '$d' > "$dst";
        fi
  - path: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root:root
    permissions: '0644'
    content: |
      BOOTPROTO=none
      DEVICE=eth0
      ONBOOT=yes
      TYPE=Ethernet
      USERCTL=no
      BRIDGE={{ IRONIC_ENDPOINT_BRIDGE }}
  - path: /etc/sysconfig/network-scripts/ifcfg-{{ IRONIC_ENDPOINT_BRIDGE }}
    owner: root:root
    permissions: '0644'
    content: |
      TYPE=Bridge
      DEVICE={{ IRONIC_ENDPOINT_BRIDGE }}
      ONBOOT=yes
      USERCTL=no
      BOOTPROTO="static"
      IPADDR={{ "{{ ds.meta_data.provisioningIP }}" }}
      PREFIX={{ "{{ ds.meta_data.provisioningCIDR }}" }}
  - path: /etc/yum.repos.d/kubernetes.repo
    owner: root:root
    permissions: '0644'
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=0
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - path : /etc/containers/registries.conf
    owner: root:root
    permissions: '0644'
    content: |
      [registries.search]
      registries = ['docker.io']

      [registries.insecure]
      registries = ['{{ REGISTRY }}']
