apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cluster.x-k8s.io/v1alpha4","kind":"MachineDeployment","metadata":{"annotations":{},"labels":{"cluster.x-k8s.io/cluster-name":"test1","nodepool":"nodepool-0"},"name":"test1","namespace":"metal3"},"spec":{"clusterName":"test1","replicas":1,"selector":{"matchLabels":{"cluster.x-k8s.io/cluster-name":"test1","nodepool":"nodepool-0"}},"template":{"metadata":{"labels":{"cluster.x-k8s.io/cluster-name":"test1","nodepool":"nodepool-0"}},"spec":{"bootstrap":{"configRef":{"apiVersion":"bootstrap.cluster.x-k8s.io/v1alpha4","kind":"KubeadmConfigTemplate","name":"test1-workers"}},"clusterName":"test1","infrastructureRef":{"apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","kind":"Metal3MachineTemplate","name":"test1-workers"},"nodeDrainTimeout":"0s","version":"v1.21.1"}}}}
    machinedeployment.clusters.x-k8s.io/revision: "1"
  creationTimestamp: "2021-11-12T21:42:40Z"
  generation: 1
  labels:
    cluster.x-k8s.io/cluster-name: test1
    nodepool: nodepool-0
  name: test1
  namespace: metal3
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1alpha4
    kind: Cluster
    name: test1
    uid: d3e80880-3a6b-457e-ba2c-fceffab2751d
  resourceVersion: "45994"
  uid: 8d60f2ac-07a2-4f3c-b484-67dbabc9e435
spec:
  clusterName: test1
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test1
      nodepool: nodepool-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test1
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: test1-workers
      clusterName: test1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
        kind: Metal3MachineTemplate
        name: test1-workers
      nodeDrainTimeout: 0s
      version: v1.21.1
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-12T21:42:49Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-11-12T21:42:49Z"
    status: "True"
    type: Available
  observedGeneration: 1
  phase: Running
  readyReplicas: 1
  replicas: 1
  selector: cluster.x-k8s.io/cluster-name=test1,nodepool=nodepool-0
  updatedReplicas: 1
