- name: Stop libvirt networks
  virt_net:
    command: destroy
    name: "{{ item.name }}"
    state: inactive
  with_items: "{{ networks }}"
  become: true

- name: Delete libvirt networks
  virt_net:
    command: undefine
    state: absent
    name: "{{ item.name }}"
  with_items: "{{ networks }}"
  become: true

# TODO: Replace with ansible community.general.nmcli?
- name: Delete bridges and veth interfaces on Ubuntu
  shell: |
     sudo ip link set baremetal down
     sudo ip link set provisioning down
     sudo ip link set ironicendpoint down
     brctl delbr baremetal || true
     brctl delbr provisioning || true
     sudo ip link del ironicendpoint || true

  when:
    - ansible_distribution == 'Ubuntu'

  become: yes
