---
  - name: Check IMAGE_OS 
    block:
      - name: Get the facts about local image
        stat:
          path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}"
        register: image_path

      - debug:
          msg: "Local image {{ RAW_IMAGE_NAME }} is found"
        when:
          - image_path.stat.exists == True

      - name: Download image.
        block:
          - debug:
              msg: "Local image {{ IMAGE_LOCATION }}/{{ IMAGE_NAME }} is not found, starting to download"

          - name: Verify specific image containing newer version of cloud-init is downloaded
            get_url:
              url: "{{ IMAGE_LOCATION }}/{{ IMAGE_NAME }}"
              dest: "{{ IRONIC_IMAGE_DIR }}/{{ IMAGE_NAME }}"
              mode: 0664

          - name: Create raw image
            shell: |
              qemu-img convert -O raw "{{ IRONIC_IMAGE_DIR }}/{{IMAGE_NAME}}" "{{ IRONIC_IMAGE_DIR }}/{{RAW_IMAGE_NAME}}"

          - name: Calculate md5sum of the image
            stat:
              path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}"
              checksum_algorithm: md5
            register: image_md5

          - name: Create the md5sum file
            copy:
              content: |
                {{ image_md5.stat.checksum }}

              dest: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}.md5sum"
              mode: 0664
        when:
          - image_path.stat.exists == False
