---
  - name: Power off "{{ BMH_NODE }}"
    k8s:
      state: present
      api_version: metal3.io/v1alpha1
      namespace: "{{ NAMESPACE }}"
      kind: BareMetalHost
      name: "{{ BMH_NODE }}"
      definition:
        metadata:
          annotations:
            reboot.metal3.io/poweroff: ""

  - name: Wait until powered off "{{ K8S_NODE }}" becomes NotReady
    k8s_info:
      api_version: v1
      kind: nodes
      name: "{{ K8S_NODE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
    register: nodes
    retries: 150
    delay: 3
    vars:
      q: "[? metadata.name == '{{ K8S_NODE }}' && status.conditions[? type=='Ready' && status!='True']]"
    until:
      - nodes is succeeded
      - nodes.resources | json_query(q) | length > 0

  - pause:
      minutes: 1

  - name: List only powered off VMs
    virt:
      command: list_vms
      state: shutdown
    register: shutdown_vms
    retries: 50
    delay: 10
    until: LIBVIRT_VM in shutdown_vms.list_vms
    become: yes
    become_user: root

  - name: Power on "{{ BMH_NODE }}"
    k8s:
      state: present
      api_version: metal3.io/v1alpha1
      kind: BareMetalHost
      name: "{{ BMH_NODE }}"
      namespace: "{{ NAMESPACE }}"
      definition:
        metadata:
          annotations:
            reboot.metal3.io/poweroff: null

  - name: List only running VMs
    virt:
      command: list_vms
      state: running
    register: running_vms
    retries: 50
    delay: 10
    until: LIBVIRT_VM in running_vms.list_vms
    become: yes
    become_user: root

  - name: Wait until powered on "{{ K8S_NODE }}" becomes Ready
    k8s_info:
      api_version: v1
      kind: nodes
      name: "{{ K8S_NODE }}"
      kubeconfig: "/tmp/kubeconfig-{{ CLUSTER_NAME }}.yaml"
      wait: True
      wait_condition:
        type: Ready
        status: True
      wait_sleep: 3
      wait_timeout: 450
